### ISSUE TITLE
Compilation Error: Mismatched Types in `gateway/src/interface/server.rs`

### ISSUE THREAD

**Issue by streetycat** [buckyos/buckyos#12]
I encountered an error during the compilation of the demo, as shown below:

error[E0308]: mismatched types
--> gateway/src/interface/server.rs:108:38
|
108 | *resp.status_mut() = status;
| ------------------ ^^^^^^ expected StatusCode, found http::status::StatusCode
| |
| expected due to the type of this binding
|
= note: http::status::StatusCode and StatusCode have similar names, but are actually distinct types
note: http::status::StatusCode is defined in crate http
--> /home/ubuntu/.cargo/registry/src/index.crates.io-6f17d22bba15001f/http-1.1.0/src/status.rs:45:1
|
45 | pub struct StatusCode(NonZeroU16);
| ^^^^^^^^^^^^^^^^^^^^^
note: StatusCode is defined in crate http
--> /home/ubuntu/.cargo/registry/src/index.crates.io-6f17d22bba15001f/http-0.2.12/src/status.rs:45:1
|
45 | pub struct StatusCode(NonZeroU16);
| ^^^^^^^^^^^^^^^^^^^^^
= note: perhaps two different versions of crate http are being used?

For more information about this error, try rustc --explain E0308.
Preliminary investigation suggests that buckyos and its dependency bucky-error depend on different versions of the http library.

**Comment by waterflier** [comment]
I checked out on a brand new Linux and the problem did not reoccur. I think it might be caused by a dependency conflict of the library version. Can you delete cargo.lock and try again?
